# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=5000)),
                ('time', models.CharField(max_length=5000)),
                ('question_amount', models.IntegerField()),
                ('subject', models.CharField(max_length=5000)),
                ('date', models.CharField(max_length=50)),
                ('answers', models.TextField()),
            ],
        ),
    ]
